// Mocks generated by Mockito 5.4.4 from annotations
// in adhd_prototype/test/features/dashboard/presentation/widgets/dashboard_build_content_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes, must_be_immutable
import 'package:adhd_prototype/features/dashboard/models/dashboard_filter_details.dart'
    as _i6;
import 'package:adhd_prototype/features/dashboard/models/dashboard_notebook_details.dart'
    as _i4;
import 'package:adhd_prototype/features/dashboard/models/dashboard_today_tasks_details.dart'
    as _i5;
import 'package:adhd_prototype/features/dashboard/presentation/blocs/dashboard_state.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DashboardStateData].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardStateData extends _i1.Mock
    implements _i2.DashboardStateData {
  MockDashboardStateData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userName => (super.noSuchMethod(
        Invocation.getter(#userName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#userName),
        ),
      ) as String);

  @override
  List<_i4.DashboardNotebookDetails> get notebookDetails => (super.noSuchMethod(
        Invocation.getter(#notebookDetails),
        returnValue: <_i4.DashboardNotebookDetails>[],
      ) as List<_i4.DashboardNotebookDetails>);

  @override
  List<_i5.DashboardTodayTasksDetails> get todayTasksDetails =>
      (super.noSuchMethod(
        Invocation.getter(#todayTasksDetails),
        returnValue: <_i5.DashboardTodayTasksDetails>[],
      ) as List<_i5.DashboardTodayTasksDetails>);

  @override
  List<_i6.DashboardFilterDetails> get filterDetails => (super.noSuchMethod(
        Invocation.getter(#filterDetails),
        returnValue: <_i6.DashboardFilterDetails>[],
      ) as List<_i6.DashboardFilterDetails>);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}
